name: fumo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0-320.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_bloc: ^8.1.3
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0


flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/image/test.gif
    - assets/image/test1.gif
    - assets/image/test2.gif
    - assets/image/test3.gif
    - assets/image/giphy.gif 
    - assets/image/giphy (1).gif
    - assets/image/giphy (2).gif
    - assets/image/giphy (3).gif
    - assets/image/giphy (4).gif
    - assets/image/giphy.gif
    - assets/image/giphy.gif
    - assets/image/giphy.gif
    - assets/image/giphy.gif