// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMAIeXBXAHrgVBg9Pq3lFmkSzCxbDOLR4',
    appId: '1:394156251902:web:016384e77d585f90b2e3af',
    messagingSenderId: '394156251902',
    projectId: 'fumo-7db0b',
    authDomain: 'fumo-7db0b.firebaseapp.com',
    storageBucket: 'fumo-7db0b.firebasestorage.app',
    measurementId: 'G-CG1266VP4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrOGw90rfokarNkYEVXoqI0bkRGw6wb1M',
    appId: '1:394156251902:android:9c04bbcb42e9102cb2e3af',
    messagingSenderId: '394156251902',
    projectId: 'fumo-7db0b',
    storageBucket: 'fumo-7db0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2p2sTx-IWsb3MRmwuWbICyvwsgBORWy0',
    appId: '1:394156251902:ios:0956f3ed42efb60eb2e3af',
    messagingSenderId: '394156251902',
    projectId: 'fumo-7db0b',
    storageBucket: 'fumo-7db0b.firebasestorage.app',
    iosClientId: '394156251902-guenhm6ranat7dq6u8dlhnggk95ia5ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.fumo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2p2sTx-IWsb3MRmwuWbICyvwsgBORWy0',
    appId: '1:394156251902:ios:0956f3ed42efb60eb2e3af',
    messagingSenderId: '394156251902',
    projectId: 'fumo-7db0b',
    storageBucket: 'fumo-7db0b.firebasestorage.app',
    iosClientId: '394156251902-guenhm6ranat7dq6u8dlhnggk95ia5ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.fumo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMAIeXBXAHrgVBg9Pq3lFmkSzCxbDOLR4',
    appId: '1:394156251902:web:9893deaef71d5167b2e3af',
    messagingSenderId: '394156251902',
    projectId: 'fumo-7db0b',
    authDomain: 'fumo-7db0b.firebaseapp.com',
    storageBucket: 'fumo-7db0b.firebasestorage.app',
    measurementId: 'G-DKVXN02G3F',
  );

}